from pydantic import BaseModel, Field

class AirQualityInput(BaseModel):
    site_latitude: float = Field(..., ge=-4.4655, le=7.6009, description="site_latitude")
    site_longitude: float = Field(..., ge=-0.1698, le=40.2855, description="site_longitude")
    city: str = Field(..., description="City")
    country: str = Field(..., description="Country")
    hour: int = Field(..., ge=9, le=14, description="hour")
    sulphurdioxide_so2_column_number_density: float = Field(..., ge=-0.0013, le=0.0023, description="sulphurdioxide_so2_column_number_density")
    sulphurdioxide_so2_column_number_density_amf: float = Field(..., ge=0.1686, le=1.7378, description="sulphurdioxide_so2_column_number_density_amf")
    sulphurdioxide_so2_slant_column_number_density: float = Field(..., ge=-0.0009, le=0.0013, description="sulphurdioxide_so2_slant_column_number_density")
    sulphurdioxide_cloud_fraction: float = Field(..., ge=-0.0300, le=0.3298, description="sulphurdioxide_cloud_fraction")
    sulphurdioxide_sensor_azimuth_angle: float = Field(..., ge=-126.2139, le=95.8227, description="sulphurdioxide_sensor_azimuth_angle")
    sulphurdioxide_sensor_zenith_angle: float = Field(..., ge=-6.4287, le=72.8407, description="sulphurdioxide_sensor_zenith_angle")
    sulphurdioxide_solar_azimuth_angle: float = Field(..., ge=-179.4196, le=-7.9628, description="sulphurdioxide_solar_azimuth_angle")
    sulphurdioxide_solar_zenith_angle: float = Field(..., ge=8.0004, le=48.8753, description="sulphurdioxide_solar_zenith_angle")
    sulphurdioxide_so2_column_number_density_15km: float = Field(..., ge=-0.0004, le=0.0005, description="sulphurdioxide_so2_column_number_density_15km")
    month: float = Field(..., ge=-0.1000, le=13.1000, description="month")
    carbonmonoxide_co_column_number_density: float = Field(..., ge=0.0098, le=0.0953, description="carbonmonoxide_co_column_number_density")
    carbonmonoxide_h2o_column_number_density: float = Field(..., ge=-422.4101, le=12475.0118, description="carbonmonoxide_h2o_column_number_density")
    carbonmonoxide_cloud_height: float = Field(..., ge=-498.7943, le=5498.7372, description="carbonmonoxide_cloud_height")
    carbonmonoxide_sensor_altitude: float = Field(..., ge=828302.2586, le=830979.6550, description="carbonmonoxide_sensor_altitude")
    carbonmonoxide_sensor_azimuth_angle: float = Field(..., ge=-115.2459, le=89.8888, description="carbonmonoxide_sensor_azimuth_angle")
    carbonmonoxide_sensor_zenith_angle: float = Field(..., ge=-5.2996, le=71.8208, description="carbonmonoxide_sensor_zenith_angle")
    carbonmonoxide_solar_azimuth_angle: float = Field(..., ge=-179.2452, le=-8.1741, description="carbonmonoxide_solar_azimuth_angle")
    carbonmonoxide_solar_zenith_angle: float = Field(..., ge=6.9191, le=49.0190, description="carbonmonoxide_solar_zenith_angle")
    nitrogendioxide_no2_column_number_density: float = Field(..., ge=-0.0000, le=0.0003, description="nitrogendioxide_no2_column_number_density")
    nitrogendioxide_tropospheric_no2_column_number_density: float = Field(..., ge=-0.0001, le=0.0003, description="nitrogendioxide_tropospheric_no2_column_number_density")
    nitrogendioxide_stratospheric_no2_column_number_density: float = Field(..., ge=0.0000, le=0.0000, description="nitrogendioxide_stratospheric_no2_column_number_density")
    nitrogendioxide_no2_slant_column_number_density: float = Field(..., ge=0.0000, le=0.0004, description="nitrogendioxide_no2_slant_column_number_density")
    nitrogendioxide_tropopause_pressure: float = Field(..., ge=6922.4172, le=11595.8333, description="nitrogendioxide_tropopause_pressure")
    nitrogendioxide_absorbing_aerosol_index: float = Field(..., ge=-2.9092, le=2.7141, description="nitrogendioxide_absorbing_aerosol_index")
    nitrogendioxide_cloud_fraction: float = Field(..., ge=-0.0470, le=0.5174, description="nitrogendioxide_cloud_fraction")
    nitrogendioxide_sensor_altitude: float = Field(..., ge=828307.4673, le=831054.7530, description="nitrogendioxide_sensor_altitude")
    nitrogendioxide_sensor_azimuth_angle: float = Field(..., ge=-126.2139, le=95.8227, description="nitrogendioxide_sensor_azimuth_angle")
    nitrogendioxide_sensor_zenith_angle: float = Field(..., ge=-6.4287, le=72.8407, description="nitrogendioxide_sensor_zenith_angle")
    nitrogendioxide_solar_azimuth_angle: float = Field(..., ge=-179.4196, le=-7.9628, description="nitrogendioxide_solar_azimuth_angle")
    nitrogendioxide_solar_zenith_angle: float = Field(..., ge=9.7844, le=48.7131, description="nitrogendioxide_solar_zenith_angle")
    formaldehyde_tropospheric_hcho_column_number_density: float = Field(..., ge=-0.0007, le=0.0024, description="formaldehyde_tropospheric_hcho_column_number_density")
    formaldehyde_tropospheric_hcho_column_number_density_amf: float = Field(..., ge=0.2261, le=2.4666, description="formaldehyde_tropospheric_hcho_column_number_density_amf")
    formaldehyde_hcho_slant_column_number_density: float = Field(..., ge=-0.0006, le=0.0012, description="formaldehyde_hcho_slant_column_number_density")
    formaldehyde_cloud_fraction: float = Field(..., ge=-0.0542, le=0.5963, description="formaldehyde_cloud_fraction")
    formaldehyde_solar_zenith_angle: float = Field(..., ge=6.7920, le=49.0149, description="formaldehyde_solar_zenith_angle")
    formaldehyde_solar_azimuth_angle: float = Field(..., ge=-179.4196, le=-7.9628, description="formaldehyde_solar_azimuth_angle")
    formaldehyde_sensor_zenith_angle: float = Field(..., ge=-6.4287, le=72.8407, description="formaldehyde_sensor_zenith_angle")
    formaldehyde_sensor_azimuth_angle: float = Field(..., ge=-126.2139, le=95.8227, description="formaldehyde_sensor_azimuth_angle")
    uvaerosolindex_absorbing_aerosol_index: float = Field(..., ge=-3.1988, le=2.7404, description="uvaerosolindex_absorbing_aerosol_index")
    uvaerosolindex_sensor_altitude: float = Field(..., ge=828288.5062, le=831244.9313, description="uvaerosolindex_sensor_altitude")
    uvaerosolindex_sensor_azimuth_angle: float = Field(..., ge=-126.2139, le=95.8227, description="uvaerosolindex_sensor_azimuth_angle")
    uvaerosolindex_sensor_zenith_angle: float = Field(..., ge=-6.4506, le=73.0816, description="uvaerosolindex_sensor_zenith_angle")
    uvaerosolindex_solar_azimuth_angle: float = Field(..., ge=-179.4196, le=-7.9628, description="uvaerosolindex_solar_azimuth_angle")
    uvaerosolindex_solar_zenith_angle: float = Field(..., ge=5.6117, le=49.1222, description="uvaerosolindex_solar_zenith_angle")
    ozone_o3_column_number_density: float = Field(..., ge=0.1013, le=0.1313, description="ozone_o3_column_number_density")
    ozone_o3_column_number_density_amf: float = Field(..., ge=1.8575, le=3.8121, description="ozone_o3_column_number_density_amf")
    ozone_o3_slant_column_number_density: float = Field(..., ge=0.2009, le=0.4631, description="ozone_o3_slant_column_number_density")
    ozone_o3_effective_temperature: float = Field(..., ge=205.5457, le=246.0460, description="ozone_o3_effective_temperature")
    ozone_cloud_fraction: float = Field(..., ge=-0.1000, le=1.1000, description="ozone_cloud_fraction")
    ozone_sensor_azimuth_angle: float = Field(..., ge=-126.2139, le=95.8227, description="ozone_sensor_azimuth_angle")
    ozone_sensor_zenith_angle: float = Field(..., ge=-6.4291, le=72.8453, description="ozone_sensor_zenith_angle")
    ozone_solar_azimuth_angle: float = Field(..., ge=-179.4196, le=-7.9628, description="ozone_solar_azimuth_angle")
    ozone_solar_zenith_angle: float = Field(..., ge=6.7989, le=49.0143, description="ozone_solar_zenith_angle")
    uvaerosollayerheight_aerosol_height: float = Field(..., ge=-57.9864, le=6746.4886, description="uvaerosollayerheight_aerosol_height")
    uvaerosollayerheight_aerosol_pressure: float = Field(..., ge=41409.9389, le=100146.7186, description="uvaerosollayerheight_aerosol_pressure")
    uvaerosollayerheight_aerosol_optical_depth: float = Field(..., ge=-0.4734, le=6.8079, description="uvaerosollayerheight_aerosol_optical_depth")
    uvaerosollayerheight_sensor_zenith_angle: float = Field(..., ge=-5.3272, le=72.6560, description="uvaerosollayerheight_sensor_zenith_angle")
    uvaerosollayerheight_sensor_azimuth_angle: float = Field(..., ge=-121.2718, le=95.2340, description="uvaerosollayerheight_sensor_azimuth_angle")
    uvaerosollayerheight_solar_azimuth_angle: float = Field(..., ge=-164.3381, le=-26.0395, description="uvaerosollayerheight_solar_azimuth_angle")
    uvaerosollayerheight_solar_zenith_angle: float = Field(..., ge=10.6703, le=44.8002, description="uvaerosollayerheight_solar_zenith_angle")
    cloud_cloud_fraction: float = Field(..., ge=-0.1000, le=1.1000, description="cloud_cloud_fraction")
    cloud_cloud_top_pressure: float = Field(..., ge=306.9146, le=104253.8458, description="cloud_cloud_top_pressure")
    cloud_cloud_top_height: float = Field(..., ge=-1155.2518, le=18964.3077, description="cloud_cloud_top_height")
    cloud_cloud_base_pressure: float = Field(..., ge=1736.3776, le=109924.9327, description="cloud_cloud_base_pressure")
    cloud_cloud_base_height: float = Field(..., ge=-1618.0521, le=17915.4714, description="cloud_cloud_base_height")
    cloud_cloud_optical_depth: float = Field(..., ge=-23.3957, le=274.8542, description="cloud_cloud_optical_depth")
    cloud_surface_albedo: float = Field(..., ge=0.0578, le=0.4507, description="cloud_surface_albedo")
    cloud_sensor_azimuth_angle: float = Field(..., ge=-120.7087, le=95.3222, description="cloud_sensor_azimuth_angle")
    cloud_sensor_zenith_angle: float = Field(..., ge=-3.3273, le=72.5630, description="cloud_sensor_zenith_angle")
    cloud_solar_azimuth_angle: float = Field(..., ge=-172.7396, le=-8.5702, description="cloud_solar_azimuth_angle")
    cloud_solar_zenith_angle: float = Field(..., ge=6.7968, le=49.0145, description="cloud_solar_zenith_angle")



class AirQualityRetrainInput(AirQualityInput):
    """
    Subclass that includes the target variable for retraining purposes.
    Inherits all features from AirQualityInput.
    """
    pm2_5: float = Field(
        ..., 
        ge=0.0, 
        le=1000.0, # Setting a high upper bound for extreme pollution events
        description="The actual PM2.5 concentration required for retraining the model."
    )